create or replace
procedure ag_get_survey_details 
(
    ag_login_id_ raw,
    participant_name_ varchar2,
    user_data_ OUT types.ref_cursor
)
as 
begin

    open user_data_ for
        select  cast(ag_login_id as varchar2(100)) as ag_login_id,
                PARTICIPANT_NAME, 
                CONSENT, 
                JUVENILE_AGE, 
                PARENT_1_NAME, 
                PARENT_2_NAME, 
                DECEASED_PARENT, 
                COUNTRY_OF_BIRTH, 
                BIRTH_DATE, 
                GENDER, 
                HEIGHT_IN, 
                HEIGHT_CM, 
                WEIGHT_LBS, 
                WEIGHT_KG, 
                PHONE_NUM, 
                ZIP_CODE, 
                DIET_TYPE, 
                MULTIVITAMIN, 
                SUPPLEMENTS, 
                LACTOSE, 
                GLUTEN, 
                FOODALLERGIES_PEANUTS, 
                FOODALLERGIES_TREENUTS, 
                FOODALLERGIES_SHELLFISH, 
                FOODALLERGIES_OTHER, 
                FOODALLERGIES_OTHER_TEXT, 
                SPECIAL_RESTRICTIONS, 
                DRINKING_WATER_SOURCE, 
                RACE, 
                RACE_OTHER, 
                CURRENT_RESIDENCE_DURATION, 
                LAST_TRAVEL, 
                LIVINGWITH, 
                DOG, 
                CAT, 
                HAND, 
                SHARED_HOUSING, 
                TANNING_BEDS, 
                TANNING_SPRAYS, 
                EXERCISE_FREQUENCY, 
                EXERCISE_LOCATION, 
                NAILS, 
                POOL_FREQUENCY, 
                SMOKING_FREQUENCY, 
                ALCOHOL_FREQUENCY, 
                TEETHBRUSHING_FREQUENCY, 
                FLOSSING_FREQUENCY, 
                COSMETICS_FREQUENCY, 
                DEODERANT_USE, 
                SLEEP_DURATION, 
                SOFTENER, 
                ANTIBIOTIC_SELECT, 
                ANTIBIOTIC_CONDITION, 
                FLU_VACCINE_DATE, 
                WEIGHT_CHANGE, 
                TONSILS_REMOVED, 
                APPENDIX_REMOVED, 
                CHICKENPOX, 
                ACNE_MEDICATION, 
                ACNE_MEDICATION_OTC, 
                CONDITIONS_MEDICATION, 
                CSECTION, 
                PKU, 
                ASTHMA, 
                SEASONAL_ALLERGIES, 
                NONFOODALLERGIES_DRUG, 
                NONFOODALLERGIES_DANDER, 
                NONFOODALLERGIES_BEESTINGS, 
                NONFOODALLERGIES_POISONIVY, 
                NONFOODALLERGIES_SUN, 
                NONFOODALLERGIES_NO, 
                IBD, 
                SKIN_CONDITION, 
                DIABETES, 
                MIGRAINE, 
                PROTEIN_PER, 
                FAT_PER, 
                CARBOHYDRATE_PER, 
                PLANT_PER, 
                ANIMAL_PER, 
                FIBER_GRAMS, 
                TYPES_OF_PLANTS, 
                PERCENTAGE_FROM_CARBS, 
                PRIMARY_VEGETABLE, 
                PRIMARY_CARB, 
                DIABETES_DIAGNOSE_DATE, 
                DIABETES_MEDICATION, 
                CONTRACEPTIVE, 
                PREGNANT, 
                PREGNANT_DUE_DATE, 
                FRAT, 
                COMMUNAL_DINING, 
                ROOMMATES, 
                MIGRAINE_FREQUENCY, 
                MIGRAINE_FACTOR_1, 
                MAINFACTOR_OTHER_1, 
                MIGRAINE_FACTOR_2, 
                MAINFACTOR_OTHER_2, 
                MIGRAINE_FACTOR_3, 
                MAINFACTOR_OTHER_3, 
                MIGRAINE_PAIN, 
                MIGRAINE_PHOTOPHOBIA, 
                MIGRAINE_PHONOPHOBIA, 
                MIGRAINE_NAUSEA, 
                MIGRAINE_AGGRAVATION, 
                MIGRAINE_AURA, 
                MIGRAINE_RELATIVES, 
                MIGRAINEMEDS, 
                ABOUT_YOURSELF_TEXT, 
                PARTICIPANT_EMAIL
        from    ag_human_survey
        where   ag_login_id = ag_login_id_ and participant_name = participant_name_;

end;

/* 
variable user_data_ REFCURSOR;
execute ag_get_survey_details('D859D003CB061C43E0408A800C5D6042', 'Duggus', :user_data_);
print user_data_;
*/
