create or replace 
PROCEDURE "REBUILD_INDEXES"
/* This procedure disables some of the table constraints. */
(
  error_flag IN OUT NUMBER
) as 
begin
    
 EXECUTE IMMEDIATE 'ALTER INDEX IDX_SLRM_SLRI REBUILD' ;  
 EXECUTE IMMEDIATE 'ALTER INDEX SEQ_NAME_INDEX REBUILD' ;  
 -- EXECUTE IMMEDIATE 'ALTER INDEX IDX_SLRM_READ_ID REBUILD' ;  
 -- EXECUTE IMMEDIATE 'ALTER INDEX IDX_SLRM_SEQ_RUN_ID REBUILD' ;  
 EXECUTE IMMEDIATE 'ALTER INDEX SEQ_NAME_SSU_ID_IDX REBUILD' ;  
 EXECUTE IMMEDIATE 'ALTER INDEX IDX_SLRM_SAMPLE_NAME REBUILD' ;  
 EXECUTE IMMEDIATE 'ALTER INDEX IDX_SLRM_SEQRUNID_SLRID REBUILD' ;  
 -- EXECUTE IMMEDIATE 'ALTER INDEX IDX_SLRM_SSU_SEQUENCE_ID REBUILD' ;  
 EXECUTE IMMEDIATE 'ALTER INDEX PK_SPLIT_LIBRARY_READ_MAP REBUILD' ;   
 -- EXECUTE IMMEDIATE 'ALTER index IX_SLRM_SRID_RID REBUILD' ; 

 COMMIT;
end rebuild_indexes;

/*
variable error_flag NUMBER;
execute REBUILD_INDEXES(:error_flag);
print error_flag;
*/