#!/usr/bin/env python
# File created on 19 Apr 2011
from __future__ import division

__author__ = "Jesse Stombaugh"
__copyright__ = "Copyright 2011, The QIIME-webdev project"
__credits__ = ["Jesse Stombaugh"]
__license__ = "GPL"
__version__ = "1.2.1-dev"
__maintainer__ = "Jesse Stombaugh"
__email__ = "jesse.stombaugh@colorado.edu"
__status__ = "Development"
 

from cogent.util.unit_test import TestCase, main
from cogent.util.misc import remove_files
from cogent.app.util import get_tmp_filename
from run_find_otus_in_database import find_otus,process_items
from os.path import join
from data_access_connections import data_access_factory
from enums import ServerConfig
from qiime.parse import parse_otu_map


class findOTUsInDB(TestCase):
    
    def setUp(self):
        """setup the test values"""
        
        self.dirs_to_remove = []
        self.files_to_remove = []
        self.tmp_dir='/tmp/'
        
        #generate random fnames for OTU maps
        self.output_otu_map=get_tmp_filename(tmp_dir=self.tmp_dir,
         prefix='otu_map1_',suffix='.txt',result_constructor=str)
        self.leftovers=get_tmp_filename(tmp_dir=self.tmp_dir,
         prefix='leftovers_',suffix='.fna',result_constructor=str)
        self.input_fasta=get_tmp_filename(tmp_dir=self.tmp_dir,
         prefix='seqs_',suffix='.fna',result_constructor=str)
        
        #write out the sequence file
        self.seqout=open(self.input_fasta,'w')
        self.seqout.write(seqs)
        self.seqout.close()
        
    def tearDown(self):
        """remove all the files after completing tests """
        
        remove_files(self.files_to_remove)
    
    def test_find_otus(self):
        """ test_find_otus: This fxn checks for otu assignment of a set of 
            sequences
        """
        #make sure files gets cleaned up
        self.files_to_remove.append(self.output_otu_map)
        self.files_to_remove.append(self.leftovers)
        self.files_to_remove.append(self.input_fasta)

        #run the fxn
        find_otus(self.input_fasta,self.leftovers,self.output_otu_map)
        data, sample_ids, otu_ids = parse_otu_map(open(self.output_otu_map))
        
        #check the outputs are correct
        self.assertEqual(sample_ids[0],'HIT')
        self.assertEqual(open(self.leftovers).read(),exp_failures)

    def test_process_items(self):
        """ test_process_items: This fxn processes the md5's and checks against
            the DB
        """
        #make sure files gets cleaned up
        self.files_to_remove.append(self.leftovers)
        self.files_to_remove.append(self.input_fasta)
        
        otu_map={}
        data_access = data_access_factory(ServerConfig.data_access_type)
        process_items(md5_list, md5_sequence_map, md5_seq_id_map, otu_map, 
                         data_access, open(self.leftovers,'w'))
        
        #check the outputs are correct
        self.assertEqual(open(self.leftovers).read(),exp_failures2)
        self.assertEqual(len(otu_map.keys()),1)
                         
map1="""\
133453	HIT
"""
seqs="""\
>MISS
AGAGUUUGAUCCUGGCUCACGAUGAACGCUGGCGGCGUGCUUAACACAUGCAAGUCGAACGGGAAUAUUGAAACUUCGGUUUUAAUUAUCUAGUGGCGGACGGGUGAGUAACGCGUGGGUAACCUGCCUUAUACAGGGGGAUAACAGUCAGAAAUGACUGCUAAUACCGCAUAAGCGCACGGAACCGCAUGGUUCUGUGUGAAAAACUCCGGUGGUAUAAGAUGGACCCGCGUUGGAUUAGCUUGUUGGUGAGGUAACGGCUCACCAAGGCGACGAUCCAUAGCCGGCCUGAGAGGGUGAACGGCCACAUUGGGACUGAGACACGGCCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGGGAAACCCUGAUGCAGCGACGCCGCGUGAAGGAAGAAGUAUCUCGGUAUGUAAACUUCUAUCAGCAGGGAAGAUAGUGACGGUACCUGACUAAGAAGCCCCGGCUAACUACGUGCCAGCAGCCGCGGUAAUACGUAGGGGGCAAGCGUUAUCCGGAUUUACUGGGUGUAAAGGGAGCGUAGACGGUGUGGCAAGUCUGAUGUGAAAGGCAUGGGCUCAACCUGUGGACUGCAUUGGAAACUGUCAUACUUGAGUGCCGGAGGGGUAAGCGGAAUNCCUAGUGUAGCGGUGAAAUGCGUAGAUAUUAGGAGGAACACCAGUGGCGAAGGCGGCUUACUGGACGGUAACUGACGUGNAGGCUCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGAAUACUAGGUGUCGGGGAGCAUGGCUCUUCGGUGCCGUCGCAAACGCAGUAAGUAUUCCACCUGGGGAGUACGUUCGCAAGAAUGAAACUCAAAGGAAUUGACGGGGACCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAAGCAACGCGAAGAACCUUACCAAAUCUUGACAUCCUCUACCGGCUCUUAAUCGAGCCUUUCCUUCGGGAAGAGUGACAGGUGGUGCAUGGUUGUCGUCAGCUCGUGUCGUGAGAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCCUAUCCUCAGUAGCCAGCAUUUAAGGUGGGCACUCUGGGGAGACUGCCAGGGAUAACCUGGAGGAAGGCGGGGAUGACGUCAAAUCAUCAUGCCCCUUAUGAUUUGGGCUACACACGUGCUACAAUGGCGUAAACAAAGGGAAGCGAACCUGUGAAGGCAAGCAAAUCCCAAAAAUAACGUCCCAGUUCGGACUGCAGUCUGCAACUCGACUGCACGAAGCUGGAAUCGCUAGUAAUCGCGGAUCAGAAUGCCGCGGUGAAUACGUUCCCGGGUCUUGUACACACCGCCCGUC
>HIT
CUGGCGGCGUGCUUAACACAUGCAAGUCGAACGAACAGACCCCUCCGGGGGGACGUGAGUGGCGGACGGGUGAGUAACGCGUGGGCAACCUACCCCACACAGGGGGACAACAGCCGGAAACGGCUGCUAAUACCGCAUAAGCGCACAGCCCCGCAUGGGGCGGUGCGGAAAGCUCCGGCGGUGUGGGAUGGGCCCGCGUCUGAUUAGCUAGUUGGCGGGGCAGCGGCCCACCAAGGCGACGAUCAGUAGCCGGCCUGAGAGGGCGGACGGCCACAUUGGGACUGAGACACGGCCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGGGGAACCCUGAUGCAGCGACGCCGCGUGAGCGAAGAAGUAUCUCGGUAUGUAAAGCUCUAUCAGCAGGGAAGAAAAUGACGGUACCUGACUAAGAAGCUCCGGCUAAAUACGUGCCAGCAGCCGCGGUAAUACGUAUGGAGCAAGCGUUAUCCGGAUUUACUGGGUGUAAAGGGAGCGCAGGCGGCGCGCCAAGUCUGGUGUGAAACCCCGGGGCUCAACCCCGGGACUGCAUUGGAAACUGGCGAGCUGGAGUGUCGGAGGGGCAGGCGGAAUUCCUGGUGUAGCGGUGAAAUGCGUAGAUAUCAGGAGGAACACCGGUGGCGAAGGCGGCCUGCUGGACGACAACUGACGCUGAGGCUCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGAAUACCAGGUGUCGGGGGGCAGGGCCCCCCGGUGCCGCAGCAAACGCAGUAAGUAUUCCACCUGGGGAGUACGUUCGCAAGAAUGAAACUCAAAGGAAUUGACGGGGACCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUUGAAGCAACGCGAAGAACCUUACCAGGCCUUGACAUCUUCCUCAGCAUAUGUAACGUAUGUUCCCUCCGGGGAGGAAAGACAGGUGGUGCAUGGUUGUCGUCAGCUCGUGUCGUGAGAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCCUGCCCCCAGUAGCCAGCGCGUGAUGGCGGGCACUCUGGGGGGACUGCCGGGGACAACCCGGAGGAAGGCGGGGACGACGUCAAAUCAUCAUGCCCCUUAUGGCCUGGGCUACACACGUGCUACAAUGGCGUGAACAAAGGGAGGCGAAGUGGCGACAUGGAGCGAAUCCCAAAAACAACGCCCCAGUUCGGAUUGUAGUCUGCAACCCGACUACAUGAAGCCGGAAUCGCUAGUAAUCGCGGAUCAGAAUGCCGCGGUGAAUACGUUCCCGGGUC
"""

exp_failures="""\
>MISS
AGAGUUUGAUCCUGGCUCACGAUGAACGCUGGCGGCGUGCUUAACACAUGCAAGUCGAACGGGAAUAUUGAAACUUCGGUUUUAAUUAUCUAGUGGCGGACGGGUGAGUAACGCGUGGGUAACCUGCCUUAUACAGGGGGAUAACAGUCAGAAAUGACUGCUAAUACCGCAUAAGCGCACGGAACCGCAUGGUUCUGUGUGAAAAACUCCGGUGGUAUAAGAUGGACCCGCGUUGGAUUAGCUUGUUGGUGAGGUAACGGCUCACCAAGGCGACGAUCCAUAGCCGGCCUGAGAGGGUGAACGGCCACAUUGGGACUGAGACACGGCCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGGGAAACCCUGAUGCAGCGACGCCGCGUGAAGGAAGAAGUAUCUCGGUAUGUAAACUUCUAUCAGCAGGGAAGAUAGUGACGGUACCUGACUAAGAAGCCCCGGCUAACUACGUGCCAGCAGCCGCGGUAAUACGUAGGGGGCAAGCGUUAUCCGGAUUUACUGGGUGUAAAGGGAGCGUAGACGGUGUGGCAAGUCUGAUGUGAAAGGCAUGGGCUCAACCUGUGGACUGCAUUGGAAACUGUCAUACUUGAGUGCCGGAGGGGUAAGCGGAAUNCCUAGUGUAGCGGUGAAAUGCGUAGAUAUUAGGAGGAACACCAGUGGCGAAGGCGGCUUACUGGACGGUAACUGACGUGNAGGCUCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGAAUACUAGGUGUCGGGGAGCAUGGCUCUUCGGUGCCGUCGCAAACGCAGUAAGUAUUCCACCUGGGGAGUACGUUCGCAAGAAUGAAACUCAAAGGAAUUGACGGGGACCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAAGCAACGCGAAGAACCUUACCAAAUCUUGACAUCCUCUACCGGCUCUUAAUCGAGCCUUUCCUUCGGGAAGAGUGACAGGUGGUGCAUGGUUGUCGUCAGCUCGUGUCGUGAGAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCCUAUCCUCAGUAGCCAGCAUUUAAGGUGGGCACUCUGGGGAGACUGCCAGGGAUAACCUGGAGGAAGGCGGGGAUGACGUCAAAUCAUCAUGCCCCUUAUGAUUUGGGCUACACACGUGCUACAAUGGCGUAAACAAAGGGAAGCGAACCUGUGAAGGCAAGCAAAUCCCAAAAAUAACGUCCCAGUUCGGACUGCAGUCUGCAACUCGACUGCACGAAGCUGGAAUCGCUAGUAAUCGCGGAUCAGAAUGCCGCGGUGAAUACGUUCCCGGGUCUUGUACACACCGCCCGUC
"""

exp_failures2="""\
>MISS
AGAGUUUGAUCCUGGCUCACGAUGAACGCUGGCGGCGUGCUUAACACAUGCAAGUCGAACGGGAAUAUUGAAACUUCGGUUUUAAUUAUCUAGUGGCGGACGGGUGAGUAACGCGUGGGUAACCUGCCUUAUACAGGGGGAUAACAGUCAGAAAUGACUGCUAAUACCGCAUAAGCGCACGGAACCGCAUGGUUCUGUGUGAAAAACUCCGGUGGUAUAAGAUGGACCCGCGUUGGAUUAGCUUGUUGGUGAGGUAACGGCUCACCAAGGCGACGAUCCAUAGCCGGCCUGAGAGGGUGAACGGCCACAUUGGGACUGAGACACGGCCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGGGAAACCCUGAUGCAGCGACGCCGCGUGAAGGAAGAAGUAUCUCGGUAUGUAAACUUCUAUCAGCAGGGAAGAUAGUGACGGUACCUGACUAAGAAGCCCCGGCUAACUACGUGCCAGCAGCCGCGGUAAUACGUAGGGGGCAAGCGUUAUCCGGAUUUACUGGGUGUAAAGGGAGCGUAGACGGUGUGGCAAGUCUGAUGUGAAAGGCAUGGGCUCAACCUGUGGACUGCAUUGGAAACUGUCAUACUUGAGUGCCGGAGGGGUAAGCGGAAUNCCUAGUGUAGCGGUGAAAUGCGUAGAUAUUAGGAGGAACACCAGUGGCGAAGGCGGCUUACUGGACGGUAACUGACGUGNAGGCUCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGAAUACUAGGUGUCGGGGAGCAUGGCUCUUCGGUGCCGUCGCAAACGCAGUAAGUAUUCCACCUGGGGAGUACGUUCGCAAGAAUGAAACUCAAAGGAAUUGACGGGGACCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAAGCAACGCGAAGAACCUUACCAAAUCUUGACAUCCUCUACCGGCUCUUAAUCGAGCCUUUCCUUCGGGAAGAGUGACAGGUGGUGCAUGGUUGUCGUCAGCUCGUGUCGUGAGAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCCUAUCCUCAGUAGCCAGCAUUUAAGGUGGGCACUCUGGGGAGACUGCCAGGGAUAACCUGGAGGAAGGCGGGGAUGACGUCAAAUCAUCAUGCCCCUUAUGAUUUGGGCUACACACGUGCUACAAUGGCGUAAACAAAGGGAAGCGAACCUGUGAAGGCAAGCAAAUCCCAAAAAUAACGUCCCAGUUCGGACUGCAGUCUGCAACUCGACUGCACGAAGCUGGAAUCGCUAGUAAUCGCGGAUCAGAAUGCCGCGGUGAAUACGUUCCCGGGUCUUGUACACACCGCCCGUC
"""

exp_otu_map_dict={'133453': ['HIT']}

md5_list=['21ef3584b2a52565a0b0b7ec408bcfeb', 
          '61a481c14f66a92ce33894c6fcba4f9e']

md5_sequence_map={'21ef3584b2a52565a0b0b7ec408bcfeb': 'AGAGUUUGAUCCUGGCUCACGAUGAACGCUGGCGGCGUGCUUAACACAUGCAAGUCGAACGGGAAUAUUGAAACUUCGGUUUUAAUUAUCUAGUGGCGGACGGGUGAGUAACGCGUGGGUAACCUGCCUUAUACAGGGGGAUAACAGUCAGAAAUGACUGCUAAUACCGCAUAAGCGCACGGAACCGCAUGGUUCUGUGUGAAAAACUCCGGUGGUAUAAGAUGGACCCGCGUUGGAUUAGCUUGUUGGUGAGGUAACGGCUCACCAAGGCGACGAUCCAUAGCCGGCCUGAGAGGGUGAACGGCCACAUUGGGACUGAGACACGGCCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGGGAAACCCUGAUGCAGCGACGCCGCGUGAAGGAAGAAGUAUCUCGGUAUGUAAACUUCUAUCAGCAGGGAAGAUAGUGACGGUACCUGACUAAGAAGCCCCGGCUAACUACGUGCCAGCAGCCGCGGUAAUACGUAGGGGGCAAGCGUUAUCCGGAUUUACUGGGUGUAAAGGGAGCGUAGACGGUGUGGCAAGUCUGAUGUGAAAGGCAUGGGCUCAACCUGUGGACUGCAUUGGAAACUGUCAUACUUGAGUGCCGGAGGGGUAAGCGGAAUNCCUAGUGUAGCGGUGAAAUGCGUAGAUAUUAGGAGGAACACCAGUGGCGAAGGCGGCUUACUGGACGGUAACUGACGUGNAGGCUCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGAAUACUAGGUGUCGGGGAGCAUGGCUCUUCGGUGCCGUCGCAAACGCAGUAAGUAUUCCACCUGGGGAGUACGUUCGCAAGAAUGAAACUCAAAGGAAUUGACGGGGACCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAAGCAACGCGAAGAACCUUACCAAAUCUUGACAUCCUCUACCGGCUCUUAAUCGAGCCUUUCCUUCGGGAAGAGUGACAGGUGGUGCAUGGUUGUCGUCAGCUCGUGUCGUGAGAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCCUAUCCUCAGUAGCCAGCAUUUAAGGUGGGCACUCUGGGGAGACUGCCAGGGAUAACCUGGAGGAAGGCGGGGAUGACGUCAAAUCAUCAUGCCCCUUAUGAUUUGGGCUACACACGUGCUACAAUGGCGUAAACAAAGGGAAGCGAACCUGUGAAGGCAAGCAAAUCCCAAAAAUAACGUCCCAGUUCGGACUGCAGUCUGCAACUCGACUGCACGAAGCUGGAAUCGCUAGUAAUCGCGGAUCAGAAUGCCGCGGUGAAUACGUUCCCGGGUCUUGUACACACCGCCCGUC',
                  '61a481c14f66a92ce33894c6fcba4f9e': 'CUGGCGGCGUGCUUAACACAUGCAAGUCGAACGAACAGACCCCUCCGGGGGGACGUGAGUGGCGGACGGGUGAGUAACGCGUGGGCAACCUACCCCACACAGGGGGACAACAGCCGGAAACGGCUGCUAAUACCGCAUAAGCGCACAGCCCCGCAUGGGGCGGUGCGGAAAGCUCCGGCGGUGUGGGAUGGGCCCGCGUCUGAUUAGCUAGUUGGCGGGGCAGCGGCCCACCAAGGCGACGAUCAGUAGCCGGCCUGAGAGGGCGGACGGCCACAUUGGGACUGAGACACGGCCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGGGGAACCCUGAUGCAGCGACGCCGCGUGAGCGAAGAAGUAUCUCGGUAUGUAAAGCUCUAUCAGCAGGGAAGAAAAUGACGGUACCUGACUAAGAAGCUCCGGCUAAAUACGUGCCAGCAGCCGCGGUAAUACGUAUGGAGCAAGCGUUAUCCGGAUUUACUGGGUGUAAAGGGAGCGCAGGCGGCGCGCCAAGUCUGGUGUGAAACCCCGGGGCUCAACCCCGGGACUGCAUUGGAAACUGGCGAGCUGGAGUGUCGGAGGGGCAGGCGGAAUUCCUGGUGUAGCGGUGAAAUGCGUAGAUAUCAGGAGGAACACCGGUGGCGAAGGCGGCCUGCUGGACGACAACUGACGCUGAGGCUCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGAAUACCAGGUGUCGGGGGGCAGGGCCCCCCGGUGCCGCAGCAAACGCAGUAAGUAUUCCACCUGGGGAGUACGUUCGCAAGAAUGAAACUCAAAGGAAUUGACGGGGACCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUUGAAGCAACGCGAAGAACCUUACCAGGCCUUGACAUCUUCCUCAGCAUAUGUAACGUAUGUUCCCUCCGGGGAGGAAAGACAGGUGGUGCAUGGUUGUCGUCAGCUCGUGUCGUGAGAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCCUGCCCCCAGUAGCCAGCGCGUGAUGGCGGGCACUCUGGGGGGACUGCCGGGGACAACCCGGAGGAAGGCGGGGACGACGUCAAAUCAUCAUGCCCCUUAUGGCCUGGGCUACACACGUGCUACAAUGGCGUGAACAAAGGGAGGCGAAGUGGCGACAUGGAGCGAAUCCCAAAAACAACGCCCCAGUUCGGAUUGUAGUCUGCAACCCGACUACAUGAAGCCGGAAUCGCUAGUAAUCGCGGAUCAGAAUGCCGCGGUGAAUACGUUCCCGGGUC'}
                  
md5_seq_id_map={'21ef3584b2a52565a0b0b7ec408bcfeb': 'MISS',
                '61a481c14f66a92ce33894c6fcba4f9e': 'HIT'}

if __name__ == "__main__":
    main()